spring:
  application:
    name: hello-spring-cloud-eureka
server:
  port: 8091
eureka:
  instance:
    #服务端，也就是当前这个项目的域名
    hostname: localhost
  #如果是服务端，以下两个都填false,客户端则填true
  client:
    register-with-eureka: false
    fetch-registry: false
    #eureka服务的路径
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/